controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: forward_command_controller/ForwardCommandController

effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: effort